name: iyandana
description: "A new Flutter project."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.9.0  # Untuk webview
  image_picker: ^1.1.2
  google_maps_flutter: ^2.9.0  # Untuk map
  geocoding: ^4.0.0  # Untuk geocode address/latlong
  multi_select_flutter: ^4.1.3  # Untuk select multiple dengan checkbox
  image: ^4.2.0  # Untuk add watermark di preview gambar
  file_picker: ^10.2.3  # Untuk pick multiple file (gambar/video)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png  # Pastikan folder ini ada dan berisi gambar
