name: iyandana
description: "A new Flutter project."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.7.0
  cloud_firestore: ^4.6.3
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.0
  google_maps_flutter: ^2.12.3
  multi_select_flutter: ^4.1.3
  file_picker: ^10.2.1
  geocoding: ^4.0.0
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/  # Pastikan folder ini ada dan berisi gambar
